#!/usr/bin/env python3
# pylint: disable=too-many-lines
"""Test GPT 5.5 context window using session-based conversation continuity.

The proxy server caches ConversationId per session. When we send only the
latest user message with a consistent X-Session-Id header, the backend
tracks the full conversation history via ConversationId.
"""
import json
import os
import sys
import time
from datetime import datetime, timezone
from typing import Any, Dict, Optional, Tuple

import requests
import tiktoken

BASE_URL = "http://localhost:8230/v1/chat/completions"
MODEL = "gpt5.5-reasoning"
SESSION_ID = "dev-test-002"

ENCODER = tiktoken.get_encoding("cl100k_base")

LOG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "test_logs")
os.makedirs(LOG_DIR, exist_ok=True)
LOG_FILE = os.path.join(
    LOG_DIR,
    f"{SESSION_ID}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.jsonl",
)

QUESTIONS = [
    "Merhaba, nasilsin? Bana kendini tanitir misin?",
    "Bana 1'den 100'e kadar olan asal sayilari listeler misin?",
    "Suanda kac asal sayi listeledin? Kac tane vardi?",
    "Bana Fibonacci dizisinin ilk 50 terimini yaz.",
    "Bu Fibonacci dizisindeki en buyuk sayi kac?",
    "Bana Python'da bir bubble sort implementasyonu yaz.",
    "Yazdigin bubble sort'un zaman karmasikligi nedir?",
    "Quick sort ile bubble sort arasindaki farklar nelerdir?",
    "Bana quick sort implementasyonu da yaz.",
    "Iki sort algoritmasini karsilastiracak bir test yaz.",
    "Bana Roman Imparatorlugu'nun cokus nedenlerini acikla.",
    "Hangi neden en onemlisiydi ve neden?",
    "Buna benzer sekilde Osmanli Imparatorlugu'nun cokus nedenleri nelerdir?",
    "Iki imparatorlugun cokus nedenleri arasinda paralellikler var mi?",
    "Bana DNA'nin yapisini acikla.",
    "DNA ve RNA arasindaki farklar nelerdir?",
    "PCR testi nasil calisir?",
    "Bana mitoz ve mayoz bolunme arasindaki farklari anlat.",
    "Fotosentez nasil gerceklesir?",
    "Fotosentez ve solunum arasindaki iliski nedir?",
    "Bana Isaac Newton'un hayatini anlat.",
    "Newton'un hareket yasalari nelerdir?",
    "Kutle cekim yasasini acikla.",
    "Einstein'in gorelilik teorisi Newton'u nasil degistirdi?",
    "Bana kuantum mekaniginin temellerini anlat.",
    "Schrodinger'in kedi paradoksunu acikla.",
    "Kuantum dolanikligi nedir?",
    "Bana kimyanin periyodik tablosunu anlat.",
    "Hangi elementler en reaktiflerdir?",
    "Bana suyun kimyasal ozelliklerini anlat.",
    "Suyun donma ve kaynama noktalari neden yuksektir?",
    "Bana dunyanin atmosferini acikla.",
    "Seracilik etkisi nedir?",
    "Kuresel islima neden oluyor?",
    "Karbon ayak izimi nasil azaltabilirim?",
    "Bana gunes enerjisini anlat.",
    "Ruzgar enerjisi nasil calisir?",
    "Nukleer enerjinin artilari ve eksileri nelerdir?",
    "Bana elektrik motorunun calisma prensibini anlat.",
    "Transformat nasil calisir?",
    "Bana internetin tarihini anlat.",
    "TCP/IP protokolu nedir?",
    "DNS nasil calisir?",
    "HTTPS ve HTTP arasindaki fark nedir?",
    "Bana blockchain teknolojisini anlat.",
    "Bitcoin nasil calisir?",
    "Kripto paralarin gelecegi nedir?",
    "Bana yapay zekanin tarihini anlat.",
    "Makine ogrenmesi nedir?",
    "Derin ogrenme ile makine ogrenmesi arasindaki fark nedir?",
    "Bana neural network'lerin yapisini anlat.",
    "Backpropagation nedir?",
    "Gradient descent nasil calisir?",
    "Bana overfitting ve underfitting arasindaki farki anlat.",
    "Regularization nedir?",
    "Bana dropout teknigini anlat.",
    "Batch normalization nedir?",
    "Bana transfer learning'i anlat.",
    "Fine-tuning nedir?",
    "Bana GPT mimarisini anlat.",
    "Transformer modeli nasil calisir?",
    "Attention mechanism nedir?",
    "Self-attention ile cross-attention arasindaki fark nedir?",
    "Bana BERT modelini anlat.",
    "BERT ve GPT arasindaki farklar nelerdir?",
    "Bana RLHF'i anlat.",
    "Bana diffusion modellerini anlat.",
    "Stable Diffusion nasil calisir?",
    "Bana GAN'lari anlat.",
    "VAE nedir?",
    "Bana reinforcement learning'i anlat.",
    "Q-learning nedir?",
    "Bana Markov decision process'i anlat.",
    "Bana Monte Carlo method'unu anlat.",
    "Bana game theory'yi anlat.",
    "Nash equilibrium nedir?",
    "Bana prisoner's dilemma'yI anlat.",
    "Bana auction theory'yi anlat.",
    "Bana mechanism design'i anlat.",
    "Bana social choice theory'yi anlat.",
    "Bana Arrow's impossibility theorem'i anlat.",
    "Bana voting systems'i anlat.",
    "Bana fair division'i anlat.",
    "Bana matching theory'yi anlat.",
    "Bana stable marriage problem'i anlat.",
    "Bana network flow theory'yi anlat.",
    "Bana max-flow min-cut theorem'u anlat.",
    "Bana graph coloring'i anlat.",
    "Bana four color theorem'u anlat.",
    "Bana traveling salesman problem'i anlat.",
    "Bana P vs NP problem'ini anlat.",
    "Bana NP-completeness'i anlat.",
    "Bana Cook-Levin theorem'u anlat.",
    "Bana approximation algorithms'i anlat.",
    "Bana randomized algorithms'i anlat.",
    "Bana online algorithms'i anlat.",
    "Bana competitive analysis'i anlat.",
    "Bana streaming algorithms'i anlat.",
    "Bana sketching algorithms'i anlat.",
    # 100-199: History, Geography, Politics
    "Bana Fransiz Devrimi'nin nedenlerini ve sonucalarini anlat.",
    "Fransiz Devrimi sirasinda Robespierre'in rolu neydi?",
    "Bana Napoleon Bonaparte'in yukselisini ve dususunu anlat.",
    "Napoleon'un Rusya seferi neden basarisiz oldu?",
    "Bana Viyana Kongresi'ni anlat.",
    "Bana Sanayi Devrimi'nin Ingiltere'de baslama nedenlerini acikla.",
    "Sanayi Devrimi sosyal yapiyi nasil degistirdi?",
    "Bana Karl Marx'in hayatini ve fikirlerini anlat.",
    "Marx'in sinif mucadelesi teorisi nedir?",
    "Bana Lenin'in Rusya'da iktidari nasil ele gecirdigini anlat.",
    "Bana Birinci Dunya Savasi'nin nedenlerini anlat.",
    "Birinci Dunya Savasi'nda Sarikamis operasyonu nasil gerceklesti?",
    "Bana Ermeni Tehciri'nin tarihsel arka planini anlat.",
    "Bana Kurtulus Savasi'nda Mustafa Kemal'in rolu nu anlat.",
    "Bana Sevr Antlasmasi'nin sartlarini anlat.",
    "Bana Lozan Antlasmasi'nin onemini acikla.",
    "Bana Ikinci Dunya Savasi'nin nedenlerini anlat.",
    "Ikinci Dunya Savasi'nda Almanya'nin Polonya'ya saldirisi nasil oldu?",
    "Bana Pearl Harbor baskinini anlat.",
    "Bana Hiroshima ve Nagasaki'ye atilan atom bombalarini anlat.",
    "Bana Nurnberg Mahkemelerini anlat.",
    "Bana Cold War donemini anlat.",
    "Bana Berlin Duvari'nin insasini ve yikilisini anlat.",
    "Bana Kuba Fuze Krizi'ni anlat.",
    "Bana Vietnam Savasi'ni anlat.",
    "Bana Kore Savasi'ni anlat.",
    "Bana Sovyetler Birligi'nin cokusunu anlat.",
    "Bana Avrupa Birligi'nin olusumunu anlat.",
    "Bana NATO'nun kurulusunu anlat.",
    "Bana BM'nin kurulusunu anlat.",
    "Bana insan haklari evrensel beyannamesini anlat.",
    "Bana apartheid rejimini anlat.",
    "Bana Nelson Mandela'nin hayatini anlat.",
    "Bana Gandhi'nin pasif direnis hareketini anlat.",
    "Bana Turkiye'de cok partili hayata gecisi anlat.",
    "Bana 1960 Darbesi'nin nedenlerini anlat.",
    "Bana 1971 Muhtirasi'ni anlat.",
    "Bana 1980 Darbesi'nin toplumsal etkilerini anlat.",
    "Bana 28 Subat Sureci'ni anlat.",
    "Bana 15 Temmuz Darbe Girsimini anlat.",
    "Bana Kibris Baris Harekati'ni anlat.",
    "Bana Kibris sorununu ve BM guvenlik konseyi kararlarini anlat.",
    "Bana Ege'de kitalik soku sorununun tarihsel arka planini anlat.",
    "Bana Turkiye-Yunanistan nufus mubadelesini anlat.",
    "Bana Lozan'da Musul sorununun nasil cozuldugunu anlat.",
    "Bana Hatay'in Turkiye'ye katilma surecini anlat.",
    "Bana Balkan Savaslari'ni anlat.",
    "Bana Trabzon Rum Imparatorlugu'nun tarihini anlat.",
    "Bana Selcuklu Imparatorlugu'nun yukselisini anlat.",
    "Bana Malazgirt Savasi'nin onemini anlat.",
    "Bana Anadolu'da Turk beyliklerinin olusumunu anlat.",
    "Bana Osmanli'nun kurulus donemini anlat.",
    "Bana Osman Gazi'nin hayatini anlat.",
    "Bana Orhan Gazi doneminde Osmanli'nin genislemesini anlat.",
    "Bana Fatih Sultan Mehmet'in Istanbul'u fethini anlat.",
    "Bana Istanbul'un fethinin dunya tarihi acisindan onemini acikla.",
    "Bana Kanuni Sultan Suleyman donemini anlat.",
    "Bana Mimar Sinan'in eserlerini anlat.",
    "Bana Barbaros Hayreddin Pasa'nin denizcilikteki basarilarini anlat.",
    "Bana Kosova Savasi'ni anlat.",
    "Bana Varna Savasi'ni anlat.",
    "Bana Ankara Savasi'nda Yildirim Bayezid'in Timur'a yenilgisini anlat.",
    "Bana Sehzade Bayezid olayini anlat.",
    "Bana Koprulu Mehmet Pasa'nin ıslahatlarini anlat.",
    "Bana III. Selim donemi ıslahatlarini anlat.",
    "Bana II. Mahmud donemi ıslahatlarini anlat.",
    "Bana Tanzimat Fermani'nin onemini acikla.",
    "Bana Islahat Fermani'ni anlat.",
    "Bana I. ve II. Mesrutiyet'in ilanini anlat.",
    "Bana Ittihat ve Terakki Cemiyeti'nin yukselisini anlat.",
    "Bana Trablusgarp ve Balkan Savaslari arasindaki iliskiyi anlat.",
    "Bana Mehmet Akif Ersoy'un hayatini ve Istiklal Marsi'ni anlat.",
    "Bana Ataturk'un inkilaplarini anlat.",
    "Bana Ataturk'un dis politika ilkelerini anlat.",
    "Bana Ataturk'un ekonomik politikalarini anlat.",
    "Bana Ataturk'un egitim politikalarini anlat.",
    "Bana Ataturk'un hukuk inkilaplarini anlat.",
    "Bana Ataturk'un kadin haklarina verdigi onemi anlat.",
    "Bana Ataturk'un tarim ve sanayi politikalarini anlat.",
    "Bana Ataturk'un kultur ve sanat politikalarini anlat.",
    "Bana Ataturk'un saglik politikalarini anlat.",
    "Bana Ataturk'un ulasim ve altyapi politikalarini anlat.",
    "Bana Ataturk'un bilim ve teknoloji politikalarini anlat.",
    "Bana Ataturk'un spor politikalarini anlat.",
    "Bana Ataturk'un din ve laiklik politikalarini anlat.",
    "Bana Ataturk'un ordu ve savunma politikalarini anlat.",
    "Bana Ataturk'un demokrasi ve cumhuriyet anlayisini anlat.",
    "Bana Ataturk'un milletvekili secim sistemini anlat.",
    "Bana Ataturk'un cumhurbaskanligi sistemini anlat.",
    "Bana Ataturk'un bakanlar kurulu sistemini anlat.",
    "Bana Ataturk'un anayasa hazirlama surecini anlat.",
    "Bana Ataturk'un parti sistemini anlat.",
    "Bana Ataturk'un secim kanununu anlat.",
    "Bana Ataturk'un belediye sistemini anlat.",
    "Bana Ataturk'un vilayet sistemini anlat.",
    "Bana Ataturk'un kaymakam sistemini anlat.",
    "Bana Ataturk'un bucak sistemini anlat.",
    "Bana Ataturk'un koy sistemini anlat.",
    "Bana Ataturk'un muhtar sistemini anlat.",
    "Bana Ataturk'un mahalle sistemini anlat.",
    "Bana Ataturk'un apartman yonetim sistemini anlat.",
    "Bana Ataturk'un site yonetim sistemini anlat.",
    "Bana Ataturk'un park ve bahce yonetim sistemini anlat.",
    "Bana Ataturk'un cadde ve sokak yonetim sistemini anlat.",
    "Bana Ataturk'un meydan yonetim sistemini anlat.",
    "Bana Ataturk'un kopru yonetim sistemini anlat.",
    "Bana Ataturk'un tunel yonetim sistemini anlat.",
    "Bana Ataturk'un metro yonetim sistemini anlat.",
    "Bana Ataturk'un tramvay yonetim sistemini anlat.",
    "Bana Ataturk'un otobus yonetim sistemini anlat.",
    "Bana Ataturk'un tren yonetim sistemini anlat.",
    "Bana Ataturk'un ucak yonetim sistemini anlat.",
    "Bana Ataturk'un gemi yonetim sistemini anlat.",
    "Bana Ataturk'un balikci yonetim sistemini anlat.",
    "Bana Ataturk'un ciftci yonetim sistemini anlat.",
    "Bana Ataturk'un coban yonetim sistemini anlat.",
    "Bana Ataturk'un avci yonetim sistemini anlat.",
    # 200-299: Science, Physics, Chemistry, Biology
    "Bana termodinamigin birinci yasasini anlat.",
    "Bana termodinamigin ikinci yasasini anlat.",
    "Bana termodinamigin ucuncu yasasini anlat.",
    "Bana termodinamigin sifirinci yasasini anlat.",
    "Bana entropi kavramini acikla.",
    "Bana entalpi kavramini acikla.",
    "Bana serbest enerji kavramini acikla.",
    "Bana Gibbs serbest enerjisini anlat.",
    "Bana Helmholtz serbest enerjisini anlat.",
    "Bana Maxwell denklemlerini anlat.",
    "Bana elektromanyetik dalgalari anlat.",
    "Bana elektromanyetik spektrumu anlat.",
    "Bana radyo dalgalarini anlat.",
    "Bana mikrodalga teknolojisini anlat.",
    "Bana kizilotesi teknolojisini anlat.",
    "Bana gorunur isik spektrumunu anlat.",
    "Bana ultraviyole isinlarini anlat.",
    "Bana X-isinlarini anlat.",
    "Bana gamma isinlarini anlat.",
    "Bana radyoaktiviteyi anlat.",
    "Bana uranyumun bozunma surecini anlat.",
    "Bana karbon-14 tarihleme yontemini anlat.",
    "Bana nukleer fisyonu anlat.",
    "Bana nukleer fizyonu anlat.",
    "Bana nukleer reaktorlerin calisma prensibini anlat.",
    "Bana CERN ve Buyuk Hadron Carpistirici'ni anlat.",
    "Bana Higgs bosonunu anlat.",
    "Bana standart modeli anlat.",
    "Bana kuarklari anlat.",
    "Bana leptonlari anlat.",
    "Bana bozonlari anlat.",
    "Bana fermiyonlari anlat.",
    "Bana parcacik fiziiginin temellerini anlat.",
    "Bana sicaklik ve isi arasindaki farki anlat.",
    "Bana ozilki ve agirlik arasindaki farki anlat.",
    "Bana Newton'un hareket yasalarini matematiksel olarak acikla.",
    "Bana momentum korunumunu anlat.",
    "Bana enerji korunumunu anlat.",
    "Bana acisal momentumu anlat.",
    "Bana tork kavramini anlat.",
    "Bana is ve enerji arasindaki iliskiyi anlat.",
    "Bana kinetik enerjiyi anlat.",
    "Bana potansiyel enerjiyi anlat.",
    "Bana elastik carpismalari anlat.",
    "Bana elastik olmayan carpismalari anlat.",
    "Bana basit harmonik hareketi anlat.",
    "Bana dalga hareketini anlat.",
    "Bana ses dalgalarinin yapisini anlat.",
    "Bana Doppler etkisini anlat.",
    "Bana interferans ve kirinim kavramlarini anlat.",
    "Bana optigi ve isigin kirilmasini anlat.",
    "Bana merceklerin calisma prensibini anlat.",
    "Bana aynalarin calisma prensibini anlat.",
    "Bana mikroskobun calisma prensibini anlat.",
    "Bana teleskobun calisma prensibini anlat.",
    "Bana elektrik alan kavramini anlat.",
    "Bana manyetik alan kavramini anlat.",
    "Bana elektromanyetik induksiyonu anlat.",
    "Bana Faraday yasasini anlat.",
    "Bana Lenz yasasini anlat.",
    "Bana Ohm yasasini anlat.",
    "Bana Kirchhoff yasalarini anlat.",
    "Bana elektrik devrelerinin temellerini anlat.",
    "Bana kondansatoru anlat.",
    "Bana bobini anlat.",
    "Bana transistoru anlat.",
    "Bana diyotu anlat.",
    "Bana LED'i anlat.",
    "Bana fotodiyodu anlat.",
    "Bana solar hucreyi anlat.",
    "Bana pillerin calisma prensibini anlat.",
    "Bana lityum-iyin pillerin calisma prensibini anlat.",
    "Bana yakit hucrelerini anlat.",
    "Bana superiletkenleri anlat.",
    "Bana kuantum tünelleme etkisini anlat.",
    "Bana kuantum bilgisayarlarin temellerini anlat.",
    "Bana kubit kavramini anlat.",
    "Bana kuantum dolanikligin bilgisayarlarla iliskisini anlat.",
    "Bana Shor algoritmasini anlat.",
    "Bana Grover algoritmasini anlat.",
    "Bana kuantum hatasi duzeltme kodlarini anlat.",
    "Bana kuantum kriptografiyi anlat.",
    "Bana kuantum anahtar dagitimini anlat.",
    "Bana BB84 protokolunu anlat.",
    "Bana E91 protokolunu anlat.",
    "Bana kuantum teleportasyonu anlat.",
    "Bana kuantum olcum postulatini anlat.",
    "Bana kuantum superpozisyonu anlat.",
    "Bana dalga fonksiyonunu anlat.",
    "Bana Schrodinger denklemini anlat.",
    "Bana Heisenberg belirsizlik ilkesini anlat.",
    "Bana Pauli dislama ilkesini anlat.",
    "Bana spin kavramini anlat.",
    "Bana izospin kavramini anlat.",
    "Bana renk yukunu anlat.",
    "Bana elektrik yukunu anlat.",
    "Bana manyetik monopollari anlat.",
    "Bana karanlik maddeyi anlat.",
    "Bana karanlik enerjiyi anlat.",
    "Bana kozmik mikrodalga arka plan isimayi anlat.",
    "Bana evrenin genislemesini anlat.",
    "Bana Big Bang teorisini anlat.",
    "Bana kara delikleri anlat.",
    "Bana Hawking radyasyonunu anlat.",
    "Bana olay ufku kavramini anlat.",
    "Bana solucan deliklerini anlat.",
    "Bana zaman yolculugunun fiziksel olanakliligini anlat.",
    "Bana paralel evren teorilerini anlat.",
    "Bana string teorisini anlat.",
    "Bana M-teorisini anlat.",
    "Bana kuantum yercekimini anlat.",
    "Bana loop kuantum yercekimini anlat.",
    "Bana holografik prensibi anlat.",
    "Bana AdS/CFT uygunlugunu anlat.",
    "Bana simetri kirilmasini anlat.",
    "Bana spontane simetri kirilmasini anlat.",
    "Bana gauge teorisini anlat.",
    "Bana Yang-Mills teorisini anlat.",
    "Bana lattice gauge teorisini anlat.",
    "Bana renormalizasyon grup denklemini anlat.",
    "Bana Feynman diyagramlarini anlat.",
    "Bana perturbasyon teorisini anlat.",
    "Bana saha teorisini anlat.",
    "Bana Lagrangian mekaniğini anlat.",
    "Bana Hamiltonian mekaniğini anlat.",
    "Bana Noether teoremini anlat.",
    "Bana klasik mekaniğin temellerini anlat.",
    "Bana analitik mekaniği anlat.",
    "Bana kanonik transformasyonlari anlat.",
    "Bana Poisson parantezini anlat.",
    "Bana Hamilton-Jacobi denklemini anlat.",
    "Bana eylem-aciklik prensibini anlat.",
    "Bana varyasyon hesabini anlat.",
    "Bana Euler-Lagrange denklemini anlat.",
    "Bana genel goreliligin matematiksel temellerini anlat.",
    "Bana Einstein saha denklemlerini anlat.",
    "Bana Schwarzschild metrigini anlat.",
    "Bana Kerr metrigini anlat.",
    "Bana Friedmann denklemlerini anlat.",
    "Bana Robertson-Walker metrigini anlat.",
    "Bana kosmolojik sabiti anlat.",
    "Bana evrenin kaderini anlat.",
    "Bana Big Crunch teorisini anlat.",
    "Bana Big Rip teorisini anlat.",
    "Bana evrenin entropisini anlat.",
    "Bana Boltzmann sabitini anlat.",
    "Bana Avogadro sayisini anlat.",
    "Bana Planck sabitini anlat.",
    "Bana isik hizinin neden bir sinir oldugunu anlat.",
    "Bana Lorentz transformasyonlarini anlat.",
    "Bana Minkowski uzayzamanini anlat.",
    "Bana ozel goreliligigin temellerini anlat.",
    "Bana zaman dilatasyonunu anlat.",
    "Bana uzunluk kisalmasini anlat.",
    "Bana relativistik momentumu anlat.",
    "Bana relativistik enerjiyi anlat.",
    "Bana E=mc^2 denklemini anlat.",
    "Bana tachyonlari anlat.",
    "Bana faster-than-light yolculugun imkansizligini anlat.",
    "Bana Alcubierre warp drive teorisini anlat.",
    "Bana wormhole'lerin genel gorelilikteki yerini anlat.",
    "Bana zamanin okunu anlat.",
    "Bana entropi ve zamanin oku arasindaki iliskiyi anlat.",
    "Bana Maxwell'in iblisini anlat.",
    "Bana Boltzmann beynini anlat.",
    "Bana quantum Zeno etkisini anlat.",
    "Bana quantum Darwinism'i anlat.",
    "Bana decoherence kavramini anlat.",
    "Bana quantum measurement teorisini anlat.",
    "Bana Copenhagen yorumunu anlat.",
    "Bana many-worlds yorumunu anlat.",
    "Bana pilot-wave teorisini anlat.",
    "Bana consistent histories yorumunu anlat.",
    "Bana quantum Bayesianism'i anlat.",
    "Bana relational quantum mechanics'i anlat.",
    "Bana QBism'i anlat.",
    "Bana ensemble yorumunu anlat.",
    "Bana transactional yorumunu anlat.",
    "Bana quantum mysticism'in neden pseudoscience oldugunu anlat.",
    "Bana quantum consciousness teorisini anlat.",
    "Bana Penrose-Hameroff teorisini anlat.",
    "Bana Orch-OR teorisini anlat.",
    "Bana microtubule'lerin kuantum bilinc ile iliskisini anlat.",
    "Bana free will theorem'u anlat.",
    "Bana Conway-Kochen teoremini anlat.",
    "Bana Bell teoremini anlat.",
    "Bana CHSH inequality'i anlat.",
    "Bana Aspect deneylerini anlat.",
    "Bana loophole-free Bell testlerini anlat.",
    "Bana local realism'in cokusunu anlat.",
    "Bana superdeterminism'i anlat.",
    "Bana retrocausality'i anlat.",
    "Bana transactional interpretation'in temellerini anlat.",
    "Bana two-state vector formalism'i anlat.",
    "Bana weak measurement kavramini anlat.",
    "Bana protective measurement kavramini anlat.",
    "Bana quantum nondemolition measurement'i anlat.",
    "Bana POVM'i anlat.",
    "Bana PVM'i anlat.",
    "Bana positive operator-valued measure'i anlat.",
    "Bana projection-valued measure'i anlat.",
    "Bana density matrix'i anlat.",
    "Bana reduced density matrix'i anlat.",
    "Bana partial trace'i anlat.",
    "Bana Schmidt decomposition'u anlat.",
    "Bana Schmidt rank'i anlat.",
    "Bana entanglement entropy'i anlat.",
    "Bana von Neumann entropy'i anlat.",
    "Bana Renyi entropy'i anlat.",
    "Bana Tsallis entropy'i anlat.",
    "Bana quantum Fisher information'i anlat.",
    "Bana quantum mutual information'i anlat.",
    "Bana quantum discord'u anlat.",
    "Bana quantum steering'i anlat.",
    "Bana entanglement witness'i anlat.",
    "Bana positive map'i anlat.",
    "Bana completely positive map'i anlat.",
    "Bana quantum channel'i anlat.",
    "Bana Kraus operator'u anlat.",
    "Bana quantum operation'i anlat.",
    "Bana quantum instrument'i anlat.",
    "Bana CP map'i anlat.",
    "Bana trace-preserving map'i anlat.",
    "Bana quantum process tomography'i anlat.",
    "Bana quantum state tomography'i anlat.",
    "Bana randomized benchmarking'i anlat.",
    "Bana quantum volume'u anlat.",
    "Bana circuit quantum electrodynamics'i anlat.",
    "Bana cavity QED'i anlat.",
    "Bana Jaynes-Cummings modelini anlat.",
    "Bana Rabi oscillation'i anlat.",
    "Bana vacuum Rabi splitting'i anlat.",
    "Bana strong coupling regime'i anlat.",
    "Bana weak coupling regime'i anlat.",
    "Bana Purcell effect'i anlat.",
    "Bana Casimir effect'i anlat.",
    "Bana Lamb shift'i anlat.",
    "Bana anomalous magnetic moment'u anlat.",
    "Bana g-2 experiment'i anlat.",
    "Bana muon g-2 anomalisini anlat.",
    # 300-399: Mathematics, Computer Science
    "Bana calculus'un temellerini anlat.",
    "Bana turev kavramini acikla.",
    "Bana integral kavramini acikla.",
    "Bana zincir kuralini anlat.",
    "Bana turev alma kurallarini anlat.",
    "Bana integral alma kurallarini anlat.",
    "Bana kismi turevleri anlat.",
    "Bana coklu integralleri anlat.",
    "Bana vektor calculus'u anlat.",
    "Bana gradient, divergence ve curl'u anlat.",
    "Bana Green teoremini anlat.",
    "Bana Stokes teoremini anlat.",
    "Bana divergence teoremini anlat.",
    "Bana line integral'i anlat.",
    "Bana surface integral'i anlat.",
    "Bana volume integral'i anlat.",
    "Bana Fourier analizini anlat.",
    "Bana Fourier transformunu anlat.",
    "Bana Laplace transformunu anlat.",
    "Bana Z transformunu anlat.",
    "Bana wavelet transformunu anlat.",
    "Bana Hilbert transformunu anlat.",
    "Bana convolution'u anlat.",
    "Bana correlation'u anlat.",
    "Bana cross-correlation'u anlat.",
    "Bana autocorrelation'u anlat.",
    "Bana power spectral density'i anlat.",
    "Bana cross-spectral density'i anlat.",
    "Bana Nyquist-Shannon sampling teoremini anlat.",
    "Bana aliasing'i anlat.",
    "Bana digital signal processing'in temellerini anlat.",
    "Bana FIR filter'lari anlat.",
    "Bana IIR filter'lari anlat.",
    "Bana Butterworth filter'i anlat.",
    "Bana Chebyshev filter'i anlat.",
    "Bana elliptic filter'i anlat.",
    "Bana Bessel filter'i anlat.",
    "Bana windowing function'lari anlat.",
    "Bana Hamming window'u anlat.",
    "Bana Hanning window'u anlat.",
    "Bana Blackman window'u anlat.",
    "Bana Kaiser window'u anlat.",
    "Bana FFT algoritmasini anlat.",
    "Bana DFT ve FFT arasindaki farki anlat.",
    "Bana Cooley-Tukey algoritmasini anlat.",
    "Bana Bluestein algoritmasini anlat.",
    "Bana Rader algoritmasini anlat.",
    "Bana chirp Z transformunu anlat.",
    "Bana Goertzel algoritmasini anlat.",
    "Bana linear algebra'nin temellerini anlat.",
    "Bana matrix operations'lari anlat.",
    "Bana determinant'i anlat.",
    "Bana trace'i anlat.",
    "Bana rank'i anlat.",
    "Bana eigenvalue ve eigenvector'u anlat.",
    "Bana singular value decomposition'u anlat.",
    "Bana principal component analysis'i anlat.",
    "Bana independent component analysis'i anlat.",
    "Bana linear discriminant analysis'i anlat.",
    "Bana QR decomposition'u anlat.",
    "Bana LU decomposition'u anlat.",
    "Bana Cholesky decomposition'u anlat.",
    "Bana Schur decomposition'u anlat.",
    "Bana Jordan canonical form'u anlat.",
    "Bana rational canonical form'u anlat.",
    "Bana minimal polynomial'i anlat.",
    "Bana characteristic polynomial'i anlat.",
    "Bana Cayley-Hamilton teoremini anlat.",
    "Bana spectral teoremini anlat.",
    "Bana normal matrix'i anlat.",
    "Bana unitary matrix'i anlat.",
    "Bana Hermitian matrix'i anlat.",
    "Bana positive definite matrix'i anlat.",
    "Bana sparse matrix'i anlat.",
    "Bana banded matrix'i anlat.",
    "Bana Toeplitz matrix'i anlat.",
    "Bana Hankel matrix'i anlat.",
    "Bana Vandermonde matrix'i anlat.",
    "Bana circulant matrix'i anlat.",
    "Bana Hadamard matrix'i anlat.",
    "Bana permutation matrix'i anlat.",
    "Bana stochastic matrix'i anlat.",
    "Bana doubly stochastic matrix'i anlat.",
    "Bana transition matrix'i anlat.",
    "Bana adjacency matrix'i anlat.",
    "Bana incidence matrix'i anlat.",
    "Bana Laplacian matrix'i anlat.",
    "Bana graph spectrum'u anlat.",
    "Bana algebraic graph theory'yi anlat.",
    "Bana spectral graph theory'yi anlat.",
    "Bana random graph theory'yi anlat.",
    "Bana Erdos-Renyi modelini anlat.",
    "Bana Barabasi-Albert modelini anlat.",
    "Bana Watts-Strogatz modelini anlat.",
    "Bana small-world network'u anlat.",
    "Bana scale-free network'u anlat.",
    "Bana power law distribution'u anlat.",
    "Bana preferential attachment'i anlat.",
    "Bana network science'in temellerini anlat.",
    "Bana community detection'i anlat.",
    "Bana modularity'yi anlat.",
    "Bana betweenness centrality'yi anlat.",
    "Bana closeness centrality'yi anlat.",
    "Bana eigenvector centrality'yi anlat.",
    "Bana PageRank'i anlat.",
    "Bana HITS algorithm'i anlat.",
    "Bana random walk'i anlat.",
    "Bana Markov chain'i anlat.",
    "Bana stationary distribution'u anlat.",
    "Bana detailed balance'i anlat.",
    "Bana ergodic theorem'i anlat.",
    "Bana mixing time'i anlat.",
    "Bana spectral gap'i anlat.",
    "Bana Cheeger inequality'i anlat.",
    "Bana expander graph'lari anlat.",
    "Bana expander mixing lemma'i anlat.",
    "Bana random walk on graph'lari anlat.",
    "Bana cover time'i anlat.",
    "Bana hitting time'i anlat.",
    "Bana commute time'i anlat.",
    "Bana effective resistance'i anlat.",
    "Bana electrical network ve random walk iliskisini anlat.",
    "Bana harmonic function'lari anlat.",
    "Bana martingale'i anlat.",
    "Bana stopping time'i anlat.",
    "Bana optional stopping theorem'u anlat.",
    "Bana Doob decomposition'u anlat.",
    "Bana Doob martingale'i anlat.",
    "Bana Azuma inequality'i anlat.",
    "Bana Hoeffding inequality'i anlat.",
    "Bana Chernoff bound'u anlat.",
    "Bana union bound'u anlat.",
    "Bana Markov inequality'i anlat.",
    "Bana Chebyshev inequality'i anlat.",
    "Bana Jensen inequality'i anlat.",
    "Bana Cauchy-Schwarz inequality'i anlat.",
    "Bana Holder inequality'i anlat.",
    "Bana Minkowski inequality'i anlat.",
    "Bana triangle inequality'i anlat.",
    "Bana AM-GM inequality'i anlat.",
    "Bana power mean inequality'i anlat.",
    "Bana rearrangement inequality'i anlat.",
    "Bana Schur inequality'i anlat.",
    "Bana Muirhead inequality'i anlat.",
    "Bana Karamata inequality'i anlat.",
    "Bana majorization'u anlat.",
    "Bana convex function'lari anlat.",
    "Bana concave function'lari anlat.",
    "Bana Jensen gap'i anlat.",
    "Bana Bregman divergence'i anlat.",
    "Bana KL divergence'i anlat.",
    "Bana JS divergence'i anlat.",
    "Bana f-divergence'i anlat.",
    "Bana total variation distance'i anlat.",
    "Bana Hellinger distance'i anlat.",
    "Bana Bhattacharyya distance'i anlat.",
    "Bana Wasserstein distance'i anlat.",
    "Bana Earth Mover's Distance'i anlat.",
    "Bana Sinkhorn algorithm'i anlat.",
    "Bana optimal transport teorisini anlat.",
    "Bana Kantorovich problem'i anlat.",
    "Bana Monge problem'i anlat.",
    "Bana Monge-Kantorovich problem'i anlat.",
    "Bana dual problem'i anlat.",
    "Bana Kantorovich dualitesini anlat.",
    "Bana Brenier theorem'u anlat.",
    "Bana McCann interpolation'u anlat.",
    "Bana displacement interpolation'u anlat.",
    "Bana barycenter'i anlat.",
    "Bana Wasserstein barycenter'i anlat.",
    "Bana entropic regularization'i anlat.",
    "Bana Sinkhorn divergence'i anlat.",
    "Bana Schrodinger bridge'i anlat.",
    "Bana Sinkhorn-Knopp algorithm'i anlat.",
    "Bana matrix scaling'i anlat.",
    "Bana vector scaling'i anlat.",
    "Bana diagonal scaling'i anlat.",
    "Bana Sinkhorn matrix'i anlat.",
    "Bana Birkhoff theorem'u anlat.",
    "Bana Birkhoff polytope'u anlat.",
    "Bana doubly stochastic matrix space'i anlat.",
    "Bana majorization polytope'u anlat.",
    "Bana Lorenz curve'u anlat.",
    "Bana Gini coefficient'i anlat.",
    "Bana entropy inequality'i anlat.",
    "Bana Schur-concavity'i anlat.",
    "Bana Schur-convexity'i anlat.",
    "Bana symmetric function'lari anlat.",
    "Bana elementary symmetric polynomial'lari anlat.",
    "Bana complete homogeneous symmetric polynomial'lari anlat.",
    "Bana power sum symmetric polynomial'lari anlat.",
    "Bana monomial symmetric polynomial'lari anlat.",
    "Bana Schur polynomial'lari anlat.",
    "Bana Jack polynomial'lari anlat.",
    "Bana Macdonald polynomial'lari anlat.",
    "Bana Hall-Littlewood polynomial'lari anlat.",
    "Bana zonal polynomial'lari anlat.",
    "Bana spherical function'lari anlat.",
    "Bana representation theory'nin temellerini anlat.",
    "Bana group representation'u anlat.",
    "Bana character theory'yi anlat.",
    "Bana irreducible representation'u anlat.",
    "Bana Schur lemma'sini anlat.",
    "Bana orthogonality relation'i anlat.",
    "Bana Peter-Weyl theorem'u anlat.",
    "Bana Haar measure'i anlat.",
    "Bana compact group'lari anlat.",
    "Bana Lie group'lari anlat.",
    "Bana Lie algebra'yi anlat.",
    "Bana Lie bracket'i anlat.",
    "Bana Lie derivative'i anlat.",
    "Bana structure constant'lari anlat.",
    "Bana Killing form'u anlat.",
    "Bana Cartan subalgebra'yi anlat.",
    "Bana root system'i anlat.",
    "Bana Dynkin diagram'i anlat.",
    "Bana Weyl group'u anlat.",
    "Bana Coxeter group'u anlat.",
    "Bana reflection group'u anlat.",
    "Bana symmetric group'u anlat.",
    "Bana alternating group'u anlat.",
    "Bana dihedral group'u anlat.",
    "Bana quaternion group'u anlat.",
    "Bana simple group'u anlat.",
    "Bana sporadic group'u anlat.",
    "Bana Monster group'u anlat.",
    "Bana Baby Monster group'u anlat.",
    "Bana Conway group'u anlat.",
    "Bana Fischer group'u anlat.",
    "Bana Mathieu group'u anlat.",
    "Bana Janko group'u anlat.",
    "Bana classification of finite simple groups'u anlat.",
    "Bana Jordan-Holder theorem'u anlat.",
    "Bana composition series'i anlat.",
    "Bana solvable group'u anlat.",
    "Bana nilpotent group'u anlat.",
    "Bana p-group'u anlat.",
    "Bana Sylow theorem'u anlat.",
    "Bana Sylow subgroup'u anlat.",
    "Bana group action'i anlat.",
    "Bana orbit-stabilizer theorem'u anlat.",
    "Bana Burnside lemma'sini anlat.",
    "Bana Polya enumeration theorem'u anlat.",
    "Bana cycle index'i anlat.",
    "Bana generating function'u anlat.",
    "Bana ordinary generating function'u anlat.",
    "Bana exponential generating function'u anlat.",
    "Bana Dirichlet generating function'u anlat.",
    "Bana Lambert series'i anlat.",
    "Bana power series'i anlat.",
    "Bana Taylor series'i anlat.",
    "Bana Laurent series'i anlat.",
    "Bana asymptotic expansion'i anlat.",
    "Bana saddle point method'unu anlat.",
    "Bana steepest descent method'unu anlat.",
    "Bana stationary phase method'unu anlat.",
    "Bana Laplace method'unu anlat.",
    "Bana Watson lemma'sini anlat.",
    "Bana method of dominant balance'i anlat.",
    "Bana perturbation series'i anlat.",
    "Bana WKB approximation'u anlat.",
    "Bana boundary layer theory'yi anlat.",
    "Bana matched asymptotic expansion'i anlat.",
    "Bana multiple scale analysis'i anlat.",
    "Bana averaging method'u anlat.",
    "Bana Poincare-Lindstedt method'unu anlat.",
    "Bana renormalization group method'unu anlat.",
    "Bana bifurcation theory'yi anlat.",
    "Bana catastrophe theory'yi anlat.",
    "Bana singularity theory'yi anlat.",
    "Bana dynamical system'lari anlat.",
    "Bana phase space'i anlat.",
    "Bana attractor'u anlat.",
    "Bana strange attractor'u anlat.",
    "Bana Lorenz attractor'u anlat.",
    "Bana chaos theory'yi anlat.",
    "Bana butterfly effect'i anlat.",
    "Bana Lyapunov exponent'i anlat.",
    "Bana Kolmogorov-Sinai entropy'i anlat.",
    "Bana ergodic theory'yi anlat.",
    "Bana mixing'i anlat.",
    "Bana Bernoulli shift'i anlat.",
    "Bana Markov shift'i anlat.",
    "Bana subshift of finite type'i anlat.",
    "Bana shift space'i anlat.",
    "Bana symbolic dynamics'i anlat.",
    "Bana kneading theory'yi anlat.",
    "Bana topological dynamics'i anlat.",
    "Bana smooth dynamics'i anlat.",
    "Bana hyperbolic dynamics'i anlat.",
    "Bana partially hyperbolic dynamics'i anlat.",
    "Bana nonuniform hyperbolicity'i anlat.",
    "Bana Pesin theory'yi anlat.",
    "Bana stable manifold theorem'u anlat.",
    "Bana unstable manifold theorem'u anlat.",
    "Bana center manifold theorem'u anlat.",
    "Bana normal form theory'yi anlat.",
    "Bana KAM theorem'u anlat.",
    "Bana Moser theorem'u anlat.",
    "Bana Nash-Moser theorem'u anlat.",
    "Bana small divisor problem'i anlat.",
    "Bana Diophantine approximation'u anlat.",
    "Bana continued fraction'lari anlat.",
    "Bana irrational number'lari anlat.",
    "Bana transcendental number'lari anlat.",
    "Bana algebraic number'lari anlat.",
    "Bana number theory'nin temellerini anlat.",
    "Bana prime number theorem'u anlat.",
    "Bana Riemann hypothesis'i anlat.",
    "Bana Riemann zeta function'u anlat.",
    "Bana Dirichlet L-function'u anlat.",
    "Bana modular form'u anlat.",
    "Bana elliptic curve'u anlat.",
    "Bana Fermat's Last Theorem'i anlat.",
    "Bana Wiles' proof'unu anlat.",
    "Bana Taniyama-Shimura conjecture'i anlat.",
    "Bana modularity theorem'u anlat.",
    "Bana BSD conjecture'i anlat.",
    "Bana Birch and Swinnerton-Dyer conjecture'i anlat.",
    "Bana abc conjecture'i anlat.",
    "Bana Mochizuki's inter-universal Teichmuller theory'i anlat.",
    "Bana Collatz conjecture'i anlat.",
    "Bana Goldbach conjecture'i anlat.",
    "Bana twin prime conjecture'i anlat.",
    "Bana Riemann hypothesis'in genellemelerini anlat.",
    "Bana generalized Riemann hypothesis'i anlat.",
    "Bana extended Riemann hypothesis'i anlat.",
    "Bana grand Riemann hypothesis'i anlat.",
    "Bana Lindelof hypothesis'i anlat.",
    "Bana Dirichlet theorem'u anlat.",
    "Bana prime number theorem'in proof'unu anlat.",
    "Bana analytic number theory'yi anlat.",
    "Bana algebraic number theory'yi anlat.",
    "Bana computational number theory'yi anlat.",
    "Bana probabilistic number theory'yi anlat.",
    "Bana additive number theory'yi anlat.",
    "Bana combinatorial number theory'yi anlat.",
    "Bana geometric number theory'yi anlat.",
    "Bana transcendental number theory'yi anlat.",
    "Bana analytic continuation'u anlat.",
    "Bana complex analysis'in temellerini anlat.",
    "Bana holomorphic function'lari anlat.",
    "Bana meromorphic function'lari anlat.",
    "Bana entire function'lari anlat.",
    "Bana Cauchy-Riemann denklemlerini anlat.",
    "Bana Cauchy integral theorem'u anlat.",
    "Bana Cauchy integral formula'sini anlat.",
    "Bana residue theorem'u anlat.",
    "Bana contour integration'u anlat.",
    "Bana argument principle'i anlat.",
    "Bana Riemann mapping theorem'u anlat.",
    "Bana conformal mapping'i anlat.",
    "Bana Schwarz lemma'sini anlat.",
    "Bana maximum modulus principle'i anlat.",
    "Bana Phragmen-Lindelof principle'i anlat.",
    "Bana harmonic function'lari anlat.",
    "Bana subharmonic function'lari anlat.",
    "Bana potential theory'yi anlat.",
    "Bana capacity theory'yi anlat.",
    "Bana extremal length'i anlat.",
    "Bana conformal invariant'lari anlat.",
    "Bana quasiconformal mapping'i anlat.",
    "Bana Teichmuller theory'yi anlat.",
    "Bana moduli space'i anlat.",
    "Bana Riemann surface'lari anlat.",
    "Bana algebraic curve'lari anlat.",
    "Bana algebraic geometry'nin temellerini anlat.",
    "Bana scheme theory'yi anlat.",
    "Bana sheaf theory'yi anlat.",
    "Bana cohomology'yi anlat.",
    "Bana homology'yi anlat.",
    "Bana homological algebra'yi anlat.",
    "Bana derived category'yi anlat.",
    "Bana triangulated category'yi anlat.",
    "Bana stable infinity-category'yi anlat.",
    "Bana higher category theory'yi anlat.",
    "Bana topos theory'yi anlat.",
    "Bana logic ve model theory'yi anlat.",
    "Bana set theory'yi anlat.",
    "Bana ZFC'yi anlat.",
    "Bana axiom of choice'u anlat.",
    "Bana continuum hypothesis'i anlat.",
    "Bana forcing'i anlat.",
    "Bana large cardinal'ari anlat.",
    "Bana inaccessible cardinal'i anlat.",
    "Bana Mahlo cardinal'i anlat.",
    "Bana measurable cardinal'i anlat.",
    "Bana Woodin cardinal'i anlat.",
    "Bana supercompact cardinal'i anlat.",
    "Bana extendible cardinal'i anlat.",
    "Bana huge cardinal'i anlat.",
    "Bana rank-into-rank cardinal'i anlat.",
    "Bana axiom of determinacy'yi anlat.",
    "Bana descriptive set theory'yi anlat.",
    "Bana Borel hierarchy'yi anlat.",
    "Bana projective hierarchy'yi anlat.",
    "Bana Wadge hierarchy'yi anlat.",
    "Bana lightface hierarchy'yi anlat.",
    "Bana boldface hierarchy'yi anlat.",
    "Bana effective descriptive set theory'yi anlat.",
    "Bana computability theory'yi anlat.",
    "Bana Turing machine'i anlat.",
    "Bana universal Turing machine'i anlat.",
    "Bana halting problem'i anlat.",
    "Bana Rice theorem'u anlat.",
    "Bana recursion theory'yi anlat.",
    "Bana arithmetical hierarchy'yi anlat.",
    "Bana analytical hierarchy'yi anlat.",
    "Bana hyperarithmetical hierarchy'yi anlat.",
    "Bana ordinal analysis'i anlat.",
    "Bana proof theory'yi anlat.",
    "Bana Gentzen's consistency proof'unu anlat.",
    "Bana cut-elimination'i anlat.",
    "Bana ordinal notation'u anlat.",
    "Bana proof ordinal'i anlat.",
    "Bana reverse mathematics'i anlat.",
    "Bana second-order arithmetic'i anlat.",
    "Bana subsystem of arithmetic'i anlat.",
    "Bana RCA_0'i anlat.",
    "Bana WKL_0'i anlat.",
    "Bana ACA_0'i anlat.",
    "Bana ATR_0'i anlat.",
    "Bana Pi^1_1-CA_0'i anlat.",
    "Bana Big Five subsystem'lari anlat.",
    "Bana ordinal strength'i anlat.",
    "Bana proof-theoretic ordinal'i anlat.",
    "Bana type theory'yi anlat.",
    "Bana dependent type theory'yi anlat.",
    "Bana Martin-Lof type theory'yi anlat.",
    "Bana homotopy type theory'yi anlat.",
    "Bana calculus of construction'u anlat.",
    "Bana CoC'u anlat.",
    "Bana Lean'i anlat.",
    "Bana Coq'u anlat.",
    "Bana Agda'yi anlat.",
    "Bana Isabelle'i anlat.",
    "Bana Hoare logic'i anlat.",
    "Bana separation logic'i anlat.",
    "Bana concurrent separation logic'i anlat.",
    "Bana rely-guarantee logic'i anlat.",
    "Bana temporal logic'i anlat.",
    "Bana modal logic'i anlat.",
    "Bana epistemic logic'i anlat.",
    "Bana deontic logic'i anlat.",
    "Bana doxastic logic'i anlat.",
    "Bana intuitionistic logic'i anlat.",
    "Bana linear logic'i anlat.",
    "Bana affine logic'i anlat.",
    "Bana relevant logic'i anlat.",
    "Bana paraconsistent logic'i anlat.",
    "Bana fuzzy logic'i anlat.",
    "Bana many-valued logic'i anlat.",
    "Bana modal mu-calculus'u anlat.",
    "Bana CTL'u anlat.",
    "Bana LTL'i anlat.",
    "Bana CTL*'i anlat.",
    "Bana model checking'i anlat.",
    "Bana SAT solver'lari anlat.",
    "Bana SMT solver'lari anlat.",
    "Bana DPLL algorithm'i anlat.",
    "Bana CDCL algorithm'i anlat.",
    "Bana resolution'u anlat.",
    "Bana Davis-Putnam procedure'unu anlat.",
    "Bana unification'u anlat.",
    "Bana term rewriting'i anlat.",
    "Bana Knuth-Bendix completion'u anlat.",
    "Bana Gröbner basis'i anlat.",
    "Bana Buchberger algorithm'i anlat.",
    "Bana F4 algorithm'i anlat.",
    "Bana F5 algorithm'i anlat.",
    "Bana involutive basis'i anlat.",
    "Bana Janet basis'i anlat.",
    "Bana Pommaret basis'i anlat.",
    "Bana involutive division'u anlat.",
    "Bana Janet division'u anlat.",
    "Bana Thomas division'u anlat.",
    "Bana Pommaret division'u anlat.",
    "Bana involutive form'u anlat.",
    "Bana involutive closure'u anlat.",
    "Bana involutive reduction'u anlat.",
    "Bana involutive autoreduction'u anlat.",
    "Bana involutive completion'u anlat.",
    "Bana involutive decomposition'u anlat.",
    "Bana involutive triangulation'u anlat.",
    "Bana involutive cone'u anlat.",
    "Bana involutive cone decomposition'u anlat.",
    "Bana involutive division algorithm'i anlat.",
    "Bana involutive basis algorithm'i anlat.",
    "Bana involutive Grobner basis'i anlat.",
    "Bana involutive Janet basis'i anlat.",
    "Bana involutive Pommaret basis'i anlat.",
    "Bana involutive Thomas basis'i anlat.",
    "Bana involutive basis completion'u anlat.",
    "Bana involutive basis reduction'u anlat.",
    "Bana involutive basis autoreduction'u anlat.",
    "Bana involutive basis decomposition'u anlat.",
    "Bana involutive basis triangulation'u anlat.",
    "Bana involutive basis cone'u anlat.",
    "Bana involutive basis cone decomposition'u anlat.",
    "Bana involutive basis division algorithm'i anlat.",
    "Bana involutive basis basis algorithm'i anlat.",
    "Bana involutive basis Grobner basis'i anlat.",
    "Bana involutive basis Janet basis'i anlat.",
    "Bana involutive basis Pommaret basis'i anlat.",
    "Bana involutive basis Thomas basis'i anlat.",
    "Bana involutive basis completion'u anlat.",
    "Bana involutive basis reduction'u anlat.",
    "Bana involutive basis autoreduction'u anlat.",
    "Bana involutive basis decomposition'u anlat.",
    "Bana involutive basis triangulation'u anlat.",
    "Bana involutive basis cone'u anlat.",
    "Bana involutive basis cone decomposition'u anlat.",
    "Bana involutive basis division algorithm'i anlat.",
    "Bana involutive basis basis algorithm'i anlat.",
    "Bana involutive basis Grobner basis'i anlat.",
    "Bana involutive basis Janet basis'i anlat.",
    "Bana involutive basis Pommaret basis'i anlat.",
    "Bana involutive basis Thomas basis'i anlat.",
]

# The request path keeps timing, response parsing, and retry state together.
# pylint: disable=too-many-locals
def send_request(
    user_msg: str, round_num: int
) -> Tuple[Optional[Dict[str, Any]], Optional[str]]:
    """Send the latest message, retrying timeout failures up to three times."""
    request_body = {
        "model": MODEL,
        "messages": [{"role": "user", "content": user_msg}],
        "stream": False,
    }
    request_headers = {"X-Session-Id": SESSION_ID}
    if api_key := os.getenv("M365_API_KEY"):
        request_headers["Authorization"] = f"Bearer {api_key}"

    max_retries = 3
    for attempt in range(1, max_retries + 1):
        t0 = time.time()
        try:
            resp = requests.post(
                BASE_URL,
                json=request_body,
                headers=request_headers,
                timeout=600,
            )
            elapsed = time.time() - t0
            if resp.status_code != 200:
                log_entry = {
                    "round": round_num,
                    "attempt": attempt,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "request": request_body,
                    "request_headers": {
                        key: value
                        for key, value in request_headers.items()
                        if key != "Authorization"
                    },
                    "response_status": resp.status_code,
                    "response_body": resp.text[:2000],
                    "elapsed_seconds": round(elapsed, 2),
                    "error": True,
                }
                with open(LOG_FILE, "a", encoding="utf-8") as f:
                    f.write(json.dumps(log_entry, ensure_ascii=False) + "\n")
                return None, f"HTTP_ERROR: HTTP {resp.status_code}: {resp.text[:500]}"
            data = resp.json()
            log_entry = {
                "round": round_num,
                "attempt": attempt,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "request": request_body,
                "request_headers": {
                        key: value
                        for key, value in request_headers.items()
                        if key != "Authorization"
                    },
                "response_status": resp.status_code,
                "response_body": data,
                "elapsed_seconds": round(elapsed, 2),
            }
            with open(LOG_FILE, "a", encoding="utf-8") as f:
                f.write(json.dumps(log_entry, ensure_ascii=False) + "\n")
            content = data["choices"][0]["message"]["content"]
            reasoning_content = data["choices"][0]["message"].get("reasoning_content", "")
            finish_reason = data["choices"][0].get("finish_reason", "")
            usage = data.get("usage", {})
            return {
                "content": content,
                "reasoning_content": reasoning_content,
                "finish_reason": finish_reason,
                "prompt_tokens": usage.get("prompt_tokens", 0),
                "completion_tokens": usage.get("completion_tokens", 0),
                "reasoning_tokens": usage.get("reasoning_tokens", 0),
                "total_tokens": usage.get("total_tokens", 0),
            }, None
        except requests.exceptions.Timeout:
            elapsed = time.time() - t0
            log_entry = {
                "round": round_num,
                "attempt": attempt,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "request": request_body,
                "request_headers": {
                        key: value
                        for key, value in request_headers.items()
                        if key != "Authorization"
                    },
                "error": "TIMEOUT",
                "elapsed_seconds": round(elapsed, 2),
            }
            with open(LOG_FILE, "a", encoding="utf-8") as f:
                f.write(json.dumps(log_entry, ensure_ascii=False) + "\n")
            if attempt < max_retries:
                print(f"  TIMEOUT on attempt {attempt}/{max_retries}, retrying in 10s...")
                sys.stdout.flush()
                time.sleep(10)
                continue
            return None, "TIMEOUT:all_retries_exhausted"
        except (requests.RequestException, ValueError, KeyError, IndexError, TypeError) as error:
            elapsed = time.time() - t0
            log_entry = {
                "round": round_num,
                "attempt": attempt,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "request": request_body,
                "request_headers": {
                        key: value
                        for key, value in request_headers.items()
                        if key != "Authorization"
                    },
                "error": str(error)[:1000],
                "elapsed_seconds": round(elapsed, 2),
            }
            with open(LOG_FILE, "a", encoding="utf-8") as f:
                f.write(json.dumps(log_entry, ensure_ascii=False) + "\n")
            return None, f"EXCEPTION: {str(error)[:500]}"
    return None, "UNKNOWN_ERROR"

# This linear driver intentionally keeps cumulative counters visible together.
# pylint: disable=too-many-locals,too-many-statements
def main() -> None:
    """Run the context-window test and print cumulative token usage."""
    round_num = 0
    total_chars = 0
    max_rounds = 500

    # Cumulative token tracking (from API usage, real BPE via tiktoken in proxy)
    cum_input_tokens = 0
    cum_output_tokens = 0
    cum_thinking_tokens = 0
    cum_total_tokens = 0

    # Per-round tiktoken counts for user message and assistant content
    cum_user_bpe = 0
    cum_assistant_bpe = 0
    cum_thinking_bpe = 0

    print(f"Model: {MODEL}")
    print(f"Session: {SESSION_ID}")
    print("Strategy: send only latest message, backend tracks history via ConversationId")
    print(f"Max rounds: {max_rounds}")
    print(f"Log file: {LOG_FILE}")
    print("Tokenizer: tiktoken cl100k_base (client-side) + proxy BPE (API usage)")
    print("=" * 80)
    sys.stdout.flush()

    while round_num < max_rounds and round_num < len(QUESTIONS):
        round_num += 1
        question = QUESTIONS[round_num - 1]
        total_chars += len(question)
        user_bpe = len(ENCODER.encode(question))
        cum_user_bpe += user_bpe

        print(f"\n[Round {round_num}] Question: {question[:80]}...")
        sys.stdout.flush()

        result, error = send_request(question, round_num)

        if error:
            print(f"  ERROR: {error}")
            print(f"\n{'=' * 80}")
            if error.startswith("TIMEOUT"):
                print(f"TIMEOUT at round {round_num} (all retries exhausted)")
            elif error.startswith("HTTP_ERROR"):
                print(f"HTTP error at round {round_num}")
            else:
                print(f"Error at round {round_num}")
            print(f"Questions asked: {round_num}")
            print(f"Total user chars: {total_chars}")
            print("\n--- Cumulative Token Summary (API usage, BPE) ---")
            print(f"  Input tokens:     {cum_input_tokens}")
            print(f"  Output tokens:    {cum_output_tokens}")
            print(f"  Reasoning tokens: {cum_thinking_tokens}")
            print(f"  Total tokens:     {cum_total_tokens}")
            print("\n--- Cumulative Token Summary (client-side tiktoken) ---")
            print(f"  User message BPE:     {cum_user_bpe}")
            print(f"  Assistant BPE:        {cum_assistant_bpe}")
            print(f"  Thinking BPE:         {cum_thinking_bpe}")
            print(f"  Total BPE (all):      {cum_user_bpe + cum_assistant_bpe + cum_thinking_bpe}")
            sys.stdout.flush()
            break

        if result is None:
            raise RuntimeError("request returned neither a result nor an error")

        content = result["content"] or ""
        reasoning = result.get("reasoning_content", "") or ""
        total_chars += len(content)

        # API usage tokens (from proxy, real BPE)
        api_input = result["prompt_tokens"]
        api_output = result["completion_tokens"]
        api_reasoning = result.get("reasoning_tokens", 0)
        api_total = result["total_tokens"]
        cum_input_tokens += api_input
        cum_output_tokens += api_output
        cum_thinking_tokens += api_reasoning
        cum_total_tokens += api_total

        # Client-side tiktoken for assistant content and thinking
        assistant_bpe = len(ENCODER.encode(content)) if content else 0
        thinking_bpe = len(ENCODER.encode(reasoning)) if reasoning else 0
        cum_assistant_bpe += assistant_bpe
        cum_thinking_bpe += thinking_bpe

        thinking_display = (
            f", reasoning_tokens={api_reasoning}, thinking_bpe={thinking_bpe}"
            if api_reasoning > 0 or thinking_bpe > 0
            else ""
        )

        print(f"  Assistant: {content[:100]}...")
        print(f"  Usage: input={api_input}, output={api_output}, total={api_total}, "
              f"finish={result['finish_reason']}{thinking_display}")
        if reasoning:
            print(f"  Thinking: {reasoning[:80]}...")
        sys.stdout.flush()

        if result["finish_reason"] == "length":
            print("  NOTE: finish_reason=length, response was truncated")

        time.sleep(2)

    else:
        print(f"\n{'=' * 80}")
        print(f"All {max_rounds} rounds completed without context window error.")
        print(f"Total rounds: {round_num}")
        print(f"Total chars (user+assistant): {total_chars}")
        print("\n--- Cumulative Token Summary (API usage, BPE) ---")
        print(f"  Input tokens:     {cum_input_tokens}")
        print(f"  Output tokens:    {cum_output_tokens}")
        print(f"  Reasoning tokens: {cum_thinking_tokens}")
        print(f"  Total tokens:     {cum_total_tokens}")
        print("\n--- Cumulative Token Summary (client-side tiktoken) ---")
        print(f"  User message BPE:     {cum_user_bpe}")
        print(f"  Assistant BPE:        {cum_assistant_bpe}")
        print(f"  Thinking BPE:         {cum_thinking_bpe}")
        print(f"  Total BPE (all):      {cum_user_bpe + cum_assistant_bpe + cum_thinking_bpe}")

if __name__ == "__main__":
    main()
